import { Geist_Mono, Space_Grotesk, Dancing_Script } from "next/font/google";
import "./globals.css";
import Header from "./_Navbar/Header";
import Footer from "./_Components/Footer";
import NavBar from "./_Navbar/NavBar";

// Load Google Fonts
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Add necessary font weights
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weight as needed
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weight as needed
});

// Metadata for SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} antialiased`}
      >
        <Header />
        {/* <NavBar/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
